name: Daily Python Job

on:
  schedule:
    - cron: "50 12 * * * "  # 每天UTC时间0点（北京时间8点）
  
  workflow_dispatch:  # 添加手动触发选项
    inputs:
      reason:
        description: '手动触发原因'
        required: false

jobs:
  execute-script:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 设置超时时间
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'  # 启用pip缓存加速

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Python script
      env:  # 读取敏感信息
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo "开始执行时间: $(date)"
        python your_script.py > output.log 2>&1  # 保存日志
        echo "执行结束时间: $(date)"
        
    - name: Upload log
      uses: actions/upload-artifact@v3
      with:
        name: execution-log
        path: output.log
